### ISSUE TITLE
Easy way to scope the notifications to the current user

### ISSUE THREAD

**Issue by bo-oz** [jonhue/notifications-rails#104]
It seems that when rendering notifications the documentation suggests to fetch the notifications with `Notification.all`, this will of course result in all the notifications, even those that don't belong to the "to-be" notified user.

Wouldn't is be nice if there was a way to easily scope the model to use the logged-in user instead? I think a lot of people use Devise for this purpose, so using that user as a starting point would be really nice. What do you think?

**Comment by jonhue** [comment]
`render_notifications` _should_ take any active record relation. So what you want to do should be possible. NotificationRenderer, however, is the only module that's missing tests, so there is a chance that this is just a bug. Does `render_notifocations` work with `Notification.all`?

**Comment by bo-oz** [comment]
Didn't think of that, you are totally right. I think it is indeed due to the fact that `render_notifications` seems not to be rendering any notifications at the moment. Anything wrong with it?

**Comment by jonhue** [comment]
As I said, this method isn't tested as of now. So it could very well be the case that it doesn't work. You can open a separate issue for that :)
