### ISSUE TITLE
render_notifications not working

### ISSUE THREAD

**Issue by DannySantos** [jonhue/notifications-rails#15]
When I use the `render_notifications` helper it renders the container div but not the notifications themselves.

This is the HAML:
```
.notifications
  %i.fa.fa-bell{class: ("error" if @unread_notifications&.any?)}
  .notification-dropdown.Dropdown__menu
    %ul.Dropdown__menu.Organisation__menu
      = render_notifications @unread_notifications if current_user && @unread_notifications
```

This is what's in `app/assets/views/notifications/push/_index.html.erb`:
```
%li.notification-container
  %h3= notification.metadata[:title]
  %p= notification.metadata[:content]
```
This is the output:
```
<div class="notifications">
  <i class="error fa fa-bell"></i>
  
  <div class="notification-dropdown Dropdown__menu" style="display: none;">
    <ul class="Dropdown__menu Organisation__menu" style="display: none;">
      <div class="notification-renderer notifications"></div>
    </ul>
  </div>
</div>
```
I'm on macOS High Sierra and using Chrome Version 67.0.3396.99.

I'm also certain that `@unread_notifications` contains some notifications.

**Comment by jonhue** [comment]
Will look into it 👍

**Comment by jonhue** [comment]
Was unable to look at this yesterday and won't be today either. Hopefully I can free up some time tomorrow.

**Comment by DannySantos** [comment]
No problem

**Comment by jonhue** [comment]
@DannySantos 

The file contents of `app/assets/views/notifications/push/_index.html.erb` are not valid ERB. It's Haml.

**Comment by jonhue** [comment]
Guess the problem is somewhere else though, as you are not getting an exception.

**Comment by jonhue** [comment]
Should be fixed now - reopen if it's still not working.

**Comment by hatedokami** [comment]
Got exactly the same rendering issue with v3.2, using ruby 2.6.3 and rails 5.2.3.

Problem lies in there: 

`app/helpers/notification_renderer_helper.rb`

in def **render_notifications**

```
....
notifications&.map do |notification|
    render_notification(notification, renderer: renderer)
end
....
```
The def itself does not return the results of **render_notification** without changing it to:

```
....
notifications&.map do |notification|
    concat render_notification(notification, renderer: renderer)
end
....
```
Does it have something to do with ruby or rails version though ?

**Comment by jonhue** [comment]
Awesome, thanks for finding the issue @hatedokami! Wanna submit a pull request?
