### ISSUE TITLE
No method Error (undefined_method 'default_category' for #<NotificationRenderer::Configuration:0x00007f4afcc226ao> Did you mean default_type?

### ISSUE THREAD

**Issue by keshavbiswa** [jonhue/notifications-rails#29]
**Describe the bug**
undefined method default_category' for #NotificationRenderer::Configuration:0x00007fdac6ed3930`

Occurs when attempting to create notification. 

Example
```ruby
notification = Notification.create target: User.first, object: Certificate.first, category: 'notification'
```
This started ever since I installed the notification_settings using

```ruby
rails g notification_settings:install
rails db:migrate
```

**Comment by jonhue** [comment]
What version of this gem did you use. The master branch from GitHub?

**Comment by keshavbiswa** [comment]
No I copied the gem from rubygems.org

**Comment by jonhue** [comment]
Please use the version of this gem from GitHub for now. I have yet to release it on rubygems.org. As you can see, the latest release there was almost a year ago.

**Comment by keshavbiswa** [comment]
Okay. I see its working perfectly fine now. Thanks

**Comment by jonhue** [comment]
If I can make time for it today, I'll push the current state of this repository to rubygems.org.

**Comment by jonhue** [comment]
I just pushed version 1.2.6 to rubygems.org.
