### ISSUE TITLE
Automatically build `notification_setting` if user doesn't have one yet

### ISSUE THREAD

**Issue by TylerRick** [jonhue/notifications-rails#33]
**Is your feature request related to a problem? Please describe.**

The Readme has this example:
```
s = User.first.notification_setting
s.settings[:enabled] = false
```

But when I tried this example after adding `notification-settings` to an existing project, I got this error instead:

```
main > s = User.first.notification_setting
=> nil

main > s.settings[:enabled] = false
NoMethodError: undefined method `settings' for nil:NilClass
```

**Describe the solution you'd like**

It would be nice if a settings target/object could safely assume that it always has an associated `notification_setting`.

It looks like this callback was added in order to help ensure that a  `notification_setting` always exists for new users:
```
before_create :create_notification_setting
```

... but that doesn't help in the case of pre-existing user records.

I propose (instead of that) overriding `notification_setting` such that it builds a new setting if one doesn't already exist:

```
      def notification_setting
        super || build_notification_setting
      end
```

I've tried it locally and it works fine...

**Describe alternatives you've considered**

Update the migration generator to create settings records for any existing [user] records.

**Comment by jonhue** [comment]
Would you be willing to submit a pull request?

**Comment by TylerRick** [comment]
Sure! Submitted #40...
