### ISSUE TITLE
Allow notifications to be enabled by default

### ISSUE THREAD

**Issue by TylerRick** [jonhue/notifications-rails#35]
**Is your feature request related to a problem? Please describe.**

Currently `settings_allow_create?` (and its sibling `category_settings_allow_create?`) return false if the notification_setting has not been explicitly enabled:
```ruby
      def settings_allow_create?
        target.notification_setting.settings.dig(:enabled)
      end
```

... which means `Notification#can_create?` will return false if a `NotificationSettings::Setting` exists for the user but doesn't have a `settings[:enabled]` key, as can be seen in this example that uses logic similar to `can_create?`:

```ruby
main > user = User.last
main > setting = user.notification_setting
=> #<NotificationSettings::Setting:0x0000557cb9086fc0
 id: nil,
 object_type: "User",
 ...
main > setting.settings.dig(:enabled)   
=> nil
main > false unless setting.settings.dig(:enabled)   
=> false
```

**Describe the solution you'd like**

I'd like notifications to be considered enabled for a user unless specifically turned off.

This would also make it more consistent with the behavior for when `target.notification_setting` is not even present (is nil):
```ruby
      def can_create?
        if target.notification_setting.present?
          ...
        true
      end
```

If the implicit value for `can_create?` is `true` if there isn't *any* setting record, then it seems the implicit value should also be `true` if there is a setting record but no settings *in* said setting record.

**Possible implementation**

Change `settings_allow_create?` (and its sibling `category_settings_allow_create?`) to specifically check for nil and return true instead of nil:
```ruby
      def settings_allow_create?
        enabled = target.notification_setting.settings.dig(:enabled)
        enabled.nil? ? true : enabled
      end
```

or simply:

```ruby
      def settings_allow_create?
        target.notification_setting.settings.fetch(:enabled) { true }
      end
```

**Describe alternatives you've considered**

If some applications actually need notifications to be _disabled_ by default, perhaps the default should be a configuration option.

```ruby
NotificationSettings.configure do |config|
  config.enabled_default = true

  # If certain categories of notifications should be enabled/disabled by default..
  config.enabled_default_by_category[:notifications] = true
  config.enabled_default_by_category[:mentions] = false
end
```

**Comment by jonhue** [comment]
Thanks for digging in. I agree that it makes sense to change this behavior. I don't think we need a configuration option. Would you be willing to submit a pull request? The solution using `fetch` looks the cleanest to me.

**Comment by TylerRick** [comment]
Sure, pull request here: #37

Yeah, I liked using `fetch` too for the simple case. Unfortunately, it doesn't scale well. In `category_settings_allow_create?`, it's already using `dig` and I can't think of a (equally nice) way to use `fetch` there.

Can't just do:
```
target.notification_setting.category_settings[category.to_sym].fetch(:enabled) { true }
```
unless we can ensure that `target.notification_setting.category_settings[:anything]` will always return a Hash (which we _could_ do if we overrode `category_settings` to use `Hash.new({})`, but that's another topic), and can't simply do

```
target.notification_setting.category_settings[category.to_sym] || true
```

Or it will never return a store `false` value.

If we didn't have to support Ruby < 2.5 or 2.6, we could at least use `yield_self` or [`then`](https://ruby-doc.org/core-2.6/Object.html#method-i-then), respectively and avoid the extra local variable... oh well, just used a local variable for now.

**Comment by jonhue** [comment]
I like using `Hash.new({})` for `category_settings` 👍 . This would allow us to remove a bunch of unnecessary logic. Therefore I don't think it makes sense to narrow down the supported Ruby versions for logic we don't really need :)
