### ISSUE TITLE
Add example of notification settings form

### ISSUE THREAD

**Issue by TylerRick** [jonhue/notifications-rails#39]
I'm trying to use `notification-settings` to help make a Notification Preferences page where users can opt in/out of different notifications/mailings—like StackOverflow (https://stackoverflow.com/users/email/settings/41234), GitHub (https://github.com/settings/notifications), and many other sites have. I found this gem when searching for a gem that helped to create such a page. I couldn't find any gems that helped directly with creating a Notification Preferences page, so I chose one instead that at least provided a nice backend. I thought it might make it easier overall.... now I'm having some doubts.

The `category_settings` on `NotificationSettings::Setting` seems to provide a decent solution for *storing* an "enabled" (opted out) setting for different notifications/mailings.

However, the fact that `category_settings` is itself a Hash, with a Hash value (like `{enabled: true}`) for each key _within_ it is making it harder to build a form for it than it otherwise might be (can't do `form_for @settings.category_settings`, for example). 

If I had just made a simple NotificationPreferences model instead, with a boolean attribute for each mailing, then it would be as simple as adding a `f.check_box` for each notification option ("category").

---

Is there an example app anywhere that demonstrates how to create a simple form for a user to edit their NotificationSettings?

Would you consider adding an example of how to use `NotificationSettings::Setting` in a form to the Readme?

I suppose the `subscribe`/`unsubscribe` API wouldn't even _need_ a form because they would just be triggered by a simple button on a resource page, but it seems like apps that use `category_settings` _would_ want some kind of page/form for editing those settings. An example of this for users and would-be users could be most helpful. :)

**Comment by jonhue** [comment]
I agree! I actually intended to document this eventually, but that never happened :)
https://github.com/jonhue/notifications-rails/tree/master/notification-settings#updating-settings

I, myself, never was a huge user of Rails's `form_for` and with the rise of frontend frameworks I basically always implemented custom form (fields).
Doing this it's actually pretty simple: 

1. you give your fields a name that represents the category you want to update
2. you implement a controller action that permits these parameters and that sets the setting record accordingly. (`s.category_settings[:enabled] = params.dig(:form, :enabled)`)

Hope that helps!

**Comment by jonhue** [comment]
If you can think of a nicer way of doing this... I am interested to hear about it 😄

**Comment by TylerRick** [comment]
That's funny. I tend to do the opposite. :smile: I try to use `form_for` for all my forms so that I can use the nicer `f.check_box :field_name` syntax in my forms...

If a model isn't already nicely usable with `form_for` directly, I usually build a form object using 
[Reform](http://trailblazer.to/gems/reform/) or [ActiveModel](https://api.rubyonrails.org/classes/ActiveModel/Model.html).

Good point about frontend frameworks. If you're using a JavaScript framework like React or Vue or Angular for the frontend, you have to build your form template without any Rails form helpers and don't have any use for `form_for`! :) Having nice form objects to handle form submission in the backend can still be useful though.

**Comment by TylerRick** [comment]
# Using Reform

My first attempt was to get it to work with Reform:

```ruby
require 'disposable/twin/property/hash'
require 'reform/form/coercion'
require 'dry/types/params'

class NotificationPreferencesForm < Reform::Form
  include Disposable::Twin::Property::Hash
  feature Coercion

  property :category_settings, field: :hash do
    Notification.unsubscribable_categories.each do |category|
      property category.to_sym do
        property :enabled, type: Types::Params::Bool
      end
    end
  end

  Notification.unsubscribable_categories.each do |category|
    unnest category, from: :category_settings
  end
end
```
... which gives us nice coercion of boolean values, among other things:
```ruby
  subject(:form) { NotificationPreferencesForm.new(notification_setting) }
  let(:params) { {
    category_settings: {
      "some_category"=>{"enabled"=>"1"}
    }
  } }

  it do
    expect(form.validate(params)).to eq(true)
    form.sync
    expect(notification_setting.category_settings[:"some_category"][:enabled]).to eq true
  end
```
Unfortunately, I couldn't get it to work in an actual form:
```haml
= form_for @form, url: [current_user, :notification_preferences] do |f|
  = f.fields_for :category_settings do |ff|
    fields...
```
... which might be me just missing something, but this is what I got:
```
undefined method `persisted?' for #<ActiveSupport::HashWithIndifferentAccess:0x0000557ebc6ca670>
```

Same error when I used the "unnested" properties instead:
```
= form_for @form, url: [current_user, :notification_preferences] do |f|
  - Notification.unsubscribable_categories.each do |category|
    = f.fields_for category do |ff|
      = ff.check_box :enabled
```

**Conclusion**: While Reform has some support for Hashes, it doesn't seem to supported nested hashes like `NotificationSettings::Setting` currently uses...

**Comment by TylerRick** [comment]
# Using ActiveModel
I think it might go something like this...
```ruby
class NotificationSettingsNode
  include ActiveModel::Model
  attribute :enabled, :boolean
end

class NotificationPreferencesForm
  include ActiveModel::Model

  Notification.unsubscribable_categories.each do |category|
    attribute category, :notification_settings_node
  end
end
```
... but I need to upgrade to Rails 5.2 first in order to be able to use [attribute API](https://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html) [in ActiveModel](https://github.com/rails/rails/pull/30985).
