### ISSUE TITLE
Pass a callable to `define_group` so evaluation of relation is deferred

### ISSUE THREAD

**Issue by TylerRick** [jonhue/notifications-rails#44]
In the [documentation](https://github.com/jonhue/notifications-rails/tree/master/notification-handler#defining-a-group), it has this example:

```ruby
NotificationHandler.configure do |config|
  config.define_group :subscribers, User.where(subscriber: true) + Admin.all
end
```

But it seems like at the time the `configure` block is run (when the app boots) is not when `User.where(subscriber: true) + Admin.all` should be evaluated. It should not be evaluated until you actually go to send a message to that group, because the set of records in the relation may have changed since the app booted up. (Also, it's inefficient to run that query unnecessarily.)

Just like Rails started requiring a callable to be passed to `scope` in Rails 4, we should require a callable to be passed to `define_group`:

```ruby
NotificationHandler.configure do |config|
  config.define_group :subscribers, -> { User.where(subscriber: true) + Admin.all }
end
```

**Comment by jonhue** [comment]
I agree! This would be a much better solution.
