### ISSUE TITLE
`deliver` not called on `NotificationMailer.push`

### ISSUE THREAD

**Issue by TylerRick** [jonhue/notifications-rails#48]
Does the existing `NotificationPusher::ActionMailer` even work? 

I noticed that in `notification-pusher/notification-pusher-actionmailer/lib/notification_pusher/action_mailer.rb`
```ruby
    def initialize(notification, options = {})
      ::NotificationPusher::ActionMailer::NotificationMailer.push(
        notification, options
      )
    end
```

, it calls the mailer action (`NotificationMailer.push`) to create the message but it never calls `deliver` (or `deliver_now` or `deliver_later`) on it... Maybe I'm just missing something, but what actually triggers the message to get *delivered*?

**Comment by jonhue** [comment]
You're right. It should call `deliver` on the mailer instance.
