### ISSUE TITLE
Change Pusher API to not push immediately when initialized

### ISSUE THREAD

**Issue by TylerRick** [jonhue/notifications-rails#49]
It seemed surprising to me that `NotificationPusher::ActionMailer` and the other pushers were trying to push directly from the `initialize` method.

Seems like it might make it a little easier to test and debug if one were able to instantiate a pusher object without it performing any action, and moving the actual action to another method like `call` or `perform` (2 generic methods I've seen before for implementing generic services) ... or `push` if you want to be more specific.

I would recommend using the generic callable interface, `call`. Then you can invoke it with the even more generic `.(*args)`, the same way you can invoke a Proc...

```ruby
SomePusher.new(notification, options).()
```

**Comment by jonhue** [comment]
This would definitely be an improvement!

**Comment by jonhue** [comment]
Though, this has to be handled in pusher as well.
https://github.com/jonhue/notifications-rails/blob/master/notification-pusher/lib/notification_pusher/notification_library.rb#L20

I guess it'd be best to just provide a `call` method in here too.

**Comment by TylerRick** [comment]
> I guess it'd be best to just provide a `call` method in here too.

I think you meant to link to https://github.com/jonhue/notifications-rails/blob/master/notification-pusher/lib/notification_pusher/pusher.rb#L13 instead of where you linked :smile: but yeah.

Cool, seems like an easy change. I'll probably submit a PR...

**Comment by jonhue** [comment]
Exactly, we should rename `NotificationPusher::Pusher#push` to `#call`

**Comment by jonhue** [comment]
I think if we go for `DeliveryMethod`, `DeliverMethodConfiguration` would make sense.

**Comment by TylerRick** [comment]
> There are two elements to this:
> 1. Making the custom pushers (like ActionMailer) a service object (separate initialization and perform)

Right.  I think we got that one done now, with #49.  See if I missed anything.

> Exactly, we should rename `NotificationPusher::Pusher#push` to `#call`

Okay by me.

> https://github.com/jonhue/notifications-rails/blob/master/notification-pusher/lib/notification_pusher/notification_library.rb#L20 was actually what I meant 

If we renamed `NotificationPusher::NotificationLibrary::InstanceMethods#push`, then you would be changing the API from:
```ruby
notification = Notification.create(target: User.first, object: Recipe.first)    
notification.push(:CustomPusher, option_one: 'value_two')     
```
to
```ruby
notification = Notification.create(target: User.first, object: Recipe.first)    
notification.call(:CustomPusher, option_one: 'value_two')     
```

Is that really what you're proposing? :confused: 

---

> 2. Separate initialization and perform in the notification-pusher API

Well, you can already initialize a `Notification` without it trying to deliver it. (`initialize_pusher` only pushes if you pass `pusher:` to `Notification.create`.) Maybe it could probably be made more separated...

What did you have in mind?

Change `initialize_pusher` to not automatically call `initiate_push`? But I think the existing `create(pusher: :Pusher)` API depends on that, right? Besides, what's the point of initializing the pusher in `after_create_commit :initialize_pusher` unless you're going to also use it? (So maybe `initialize_pusher` should be renamed to `initiate_push`.)

(Not that I would mind removing that API and the `attr_accessor :pusher` and just requiring people to explicitly call `notification.push` or `notification.deliver`. But I have nothing to urge if you want to keep it...)

**Comment by jonhue** [comment]
I was thinking about adding a method `#call`

```ruby
notification = Notification.create(target: User.first, object: Recipe.first)    
notification.push(:CustomPusher, option_one: 'value_two').call
```
