### ISSUE TITLE
Handle/validate missing Notification#target

### ISSUE THREAD

**Issue by TylerRick** [jonhue/notifications-rails#50]
Is a `target` record required to create a `Notification`?

Apparently it is because I got this error when I tried to create one without a `target`:
```
     NoMethodError:
       undefined method `notification_setting' for nil:NilClass
     # notifications-rails/notification-settings/lib/notification_settings/notification_library.rb:32:in `can_create?'
     # in `can_create?'
```

- `before_create :validate_create` calls
- `can_create?` calls
- `target.notification_setting.present?`

Should we require a `target` more directly and explicitly?

Like add a `validates :target, presence: true`?

It doesn't look like there are any validations on models yet... I'm curious why not.

I guess users would have to actually check `notification.errors` (including the one returned from `user.notify`) if they want to know why it didn't get created.

Currently the other reason a notification might not get created is that  `before_create :validate_create` throws `:abort`. Is there any way to check _why_ it wasn't able to be created in that case, in case I wanted to log or report whether the notification was sent out and why not (was it because the recipient's status was in a `do_not_notify_status`? was it because they have this pusher turned off for this category? was it because they have this pusher turned off in general? etc.)?

Would it be worth considering just adding validation errors _instead_ of using a `before_create`? Then a user could simply check `notification.errors` to learn the reason it couldn't be created...

**Comment by jonhue** [comment]
Yep, that would be a change worthwhile.
