### ISSUE TITLE
Swappable pushers (separate pusher name/key from pusher class)

### ISSUE THREAD

**Issue by TylerRick** [jonhue/notifications-rails#51]
Currently, when you define a pusher, you give it a single name, which is used both as a key (in the settings hash, for example) _and_ to look up a constant under `NotificationPusher` to get the class that implements/provides that pusher:

```ruby
NotificationPusher.configure do |config|
  config.define_pusher name, options
end
```

I think it would be helpful to make a separation between the key/name used to identify the pusher and the class that provides that ability.

This would let you use a more generic name like `:email` as they key. This would in turn make things more swappable, so you could later change to a different pusher that provides pushing to "email" and things would keep working. 

Currently I believe that would not be the case because it looks up / stores the actual class name, like `ActionMailer`, in the settings hash. But really, a user only cares whether notifications are enabled or disabled for "email" or "SMS" or whatever generic delivery method. The specific implementation used for that delivery type shouldn't be stored in that hash. 

As an inspiration/example for this, consider Rails's [Attributes API](https://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html):
```ruby
# config/initializers/types.rb
ActiveRecord::Type.register(:money, MoneyType)
```

**Comment by jonhue** [comment]
Sounds good.

**Comment by TylerRick** [comment]
Something like this perhaps?
```
config.define_pusher :email: :ActionMailer, from: 'my@email.com'
config.define_pusher :email: :SimpleMailer, from: 'my@email.com'

config.define_pusher :push, :OneSignal, app_id: '...'

config.define_pusher :sms, :SMSEasy, app_id: '...'
config.define_pusher :sms, :TwilioSMS, app_id: '...'

config.define_pusher :fax, :DoPeopleStillUseFaxes, from: '123457890'
config.define_pusher :voicemail, :SomeTextToSpeechAutomatedDialerThing
config.define_pusher :carrier_pigeon, :PigeonGram
config.define_pusher :smoke_signal, :SmokeSignalsDotCom
```
(the names being service-agnostic names corresponding to different ways users could choose to receive notifications)

```ruby
    def define_pusher(name, klass, options = {})
      pushers[name] = ::NotificationPusher::Pusher.new(klass, options)
    end
```
`klass could be a constant symbol like the current API (would check for it under `NotificationPusher::` first but still work for fully qualified constant name) or an actual constant.

Looks like this would be a breaking change...

Speaking of breaking changes, do you like the name `Pusher`? I think it's _pretty_ good, but when you start talking about a "push" Pusher, it starts to sound a little bit silly/confusing. Just something to think about...

What about calling them `DeliveryMethod`s? You can _deliver_ notifications by email, SMS, push, etc. But is it accurate to say you _push_ notifications via any option you can imagine? It's also what [ActionMailer](https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration) calls its option, not that we have to copy them.

**Comment by jonhue** [comment]
I think we can go with that. I also like the idea of renaming `Pusher` to `DeliveryMethod`. As far as I can see, this change wouldn't even require the 'pushers' itself to change. They only depend on `NotificationPusher`.
