### ISSUE TITLE
Add an ActionMailer notification-pusher that lets you use existing mailers and templates

### ISSUE THREAD

**Issue by TylerRick** [jonhue/notifications-rails#53]
I have an app that already has a bunch of different mailers that are used to send different types of notifications. So far, email notifications are the only kind it has, but I want to (1) add the ability to unsubscribe (opt out) from different notifications/categories (which `notification-settings` may help with) and (2) start adding a framework that will allow sending notifications via different methods eventually.

I looked briefly at using [`notification-pusher-actionmailer`](https://github.com/jonhue/notifications-rails/tree/master/notification-pusher/notification-pusher-actionmailer) but decided I don't really like how it would make me restructure/throw away all my mailers/templates if I wanted to use it.

At first glance anyway, the provided ActionMailer pusher seems like an unnecessary additional abstraction that actually prevents you from accessing most of the ActionMailer API. It only gives you a subset of functionality—a "least common denominator": the ability to supply a template, and specify `to`, `from`, and `layout`.

But [ActionMailer](https://guides.rubyonrails.org/action_mailer_basics.html) _already_ provides excellent abstractions and DSL for specifying those and so many other things. Why not just use it directly? A couple of things that you can do through the normal mailer API that you apparently can't do with a notification sent through `notification-pusher-actionmailer` include:
- specify multiple to recipients
- specify cc/bcc recipients
- multipart emails
- attachments
- group related messages together in different mailers (each of which may have different defaults (`from:`, etc.))

`notification-pusher-actionmailer` also depends on `notification-renderer` ... which might have _some_ advantages (like using the same system for emails that you use for rendering notifications on a web page), but I haven't needed/added that dependency _yet_, and it seems like an unnecessarily different (and less flexible) way of doing things for those used to just using `ActionMailer::Base` directly... and it would require a fair bit of work to migrate...

If I wanted to migrate from my existing mailers to use the provided ActionMailer pusher, it looks like these are some of the changes I'd have to make:
- create a new notification type for each mailer action that I wanted to use as a notification
- remove the mailer action from the mailer class it's in now; potentially remove the mailers too if they become empty
- move and rename the template to `_actionmailer.html.erb` under the 
- pass data to the template via `notification.metadata` instead of via instance variables in the mailer action

I think that approach makes a lot of sense for really short notifications that could be sent via any pusher. Some delivery methods (like SMS and push notifications) really only work with short messages, after all. And maybe I'll come back around to that option once I actually add notification methods other than email...

But if you already have long, "rich" HTML mails that you use for notifications, I wonder if it's worth switching everything to `notification-renderer` right off the bat.

Maybe I'm abusing the term "notification" and trying to us this system for something it wasn't designed for...?

---

In any case, I started exploring the option of creating an alternative ActionMailer pusher that actually lets you specify an existing mailer/action to use "_in situ_".

I figure it should be possible to create a thin adapter between the Pusher API and existing mailers, and provide a way to sort of "point" or "link" a notification to an _existing_ mailer action that can be used to deliver it.

I guess there's nothing stopping me from writing my own pusher that does this. Just wondering if anyone else had this need, and what the best approach would be...

## How to send a single notification that gets sent to multiple people via a single email message?

A few of my existing mailer actions currently send a single email to multiple recipients (so that all the recipients can see each other's names in the `To:` line of the email). Is there any way to make that work?

It seems like the current Notification structure limits you to having only one target record per notification.
(See #52.)

## What to call this new pusher?

I'd kind of like to just call it `ActionMailer` like the one included with `notifications-rails` ... esp. since the pusher name is used as a key in the settings hash. Maybe I should avoid using the same name as the provided mail pusher. But if I were to use some custom-sounding name like `ExistingMailerAdapter`, that would make a poor key for the settings hash and might prevent me from swapping/switching to a different mail pusher later (#51) (without doing a data migration). 

## Potential advantages:
- easier to integrate with an existing "legacy" system
- less of a barrier to entry for potential users considering using this project
- could use as an intermediate step before fully transitioning to a more pusher-agnostic approach
- allows richer, multi-part, etc. emails

**Comment by TylerRick** [comment]
Here's a first version of my proposed "existing mailer" pusher:
```ruby
module NotificationPusher
  class ActionMailer
    attr_reader :options

    def initialize(
      notification,
      **options
    )
      @notification = notification
      @options = options
      self.()
    end

    def call
      mailer_class
        .with(params)
        .public_send(mailer_action, *args)
        .public_send(deliver_method)
    end

    def mailer_class
      @options[:mailer] || get_mailer_class_from_mail_name
    end
    def mailer_action
      @options[:action] || get_mailer_action_from_mail_name
    end

    # These will be available as `params` inside the mailer action
    def params
      {
        notification: @notification,
        **@options.except(:args)
      }
    end

    def args
      @options[:args]
    end

    def get_mailer_class_from_mail_name
      mail_name_parts[0].camelize.constantize
    end

    def get_mailer_action_from_mail_name
      mail_name_parts[1].to_sym
    end

    # Fully qualified internal name of an email (or set of emails), in the form
    # "%{mailer_name}.%{mailer_action}"
    def mail_name
      @mail_name ||= (
        mail_name = @options[:mail_name] || @options[:category]
        mail_name && Notification.normalize_mail_name(mail_name)
      )
    end
    def mail_name!
      mail_name or raise "no mail_name was provided"
    end
    def mail_name_parts
      mail_name!.split('.')
    end

    def deliver_method
      @options[:deliver_method] || default_deliver_method
    end

    def default_deliver_method
      :deliver_later
    end
  end
end
```
```ruby
NotificationPusher.configure do |config|                                        
  config.define_pusher :ActionMailer, deliver_method: :deliver_on_commit
end
```

Then I added this `deliver` method to the `Notification` model to provide a convenient interface, and to work around #47...
```ruby
class Notification < NotificationHandler::Notification
  ...

  # If user is unsubscribed, does nothing.
  # If user is subscribed, delivers the email.
  # Usage: deliver_by_mail(*args_for_mailer_action)
  def deliver(*args)
    return unless can_create?
    push(
      :ActionMailer,
      category: category,
      args: args
    )
  end
end
```

This lets you use it something like this:
```ruby
      user.notify(object: self, category: 'SomeMailer.some_action')
        .deliver(self, user)
```

I like it pretty well so far, but it's pretty early....

Any thoughts or suggestions?

**Comment by jonhue** [comment]
As for sending _one_ notification to multiple recipients: For now you could attach the list of recipients to the metadata of the notification. I know not a very nice solution. The alternative is to create a class `Group` that encapsulates this information. Ultimately, I think that it would make sense to add this to the gem itself.

**Comment by jonhue** [comment]
As for using this gem for 'larger' things than what is usually thought of as a notification.
I think that generally this gem should work for both, small and large, notifications as they have a lot in common. But still, as you pointed out, there are some important differences. Originally, I designed this gem to be used in an application that relied mainly on push notifications.

**Comment by jonhue** [comment]
Looking at your take on a pusher: I think that this _could_ be incorporated fairly easily into the existing ActionMailer pusher. One would just have to swap `get_mailer_class_from_mail_name` and `get_mailer_action_from_mail_name` for the then default `NotificationMailer` that relies on notification-renderer.

**Comment by TylerRick** [comment]
Thanks for the feedback!

Glad to hear that it _should_ work to use with larger notifications as well (since that's what I'm trying to use it for currently :smile:)...

Cool, I hadn't even seriously considered incorporating this into the existing ActionMailer pusher! But maybe we could... I'll have to look into that possibility and submit a PR if I can come up with something that could be used in either way...

I guess we'd want to remove the hard dependency on `notification-renderer` and only use it if it's available. Maybe that could still be the default mailer if the const is defined...

**Comment by jonhue** [comment]
Good point about the renderer dependency!
We could make it optional by leaving it to the user to require it if need be.
