### ISSUE TITLE
Make sure pusher constant lookup works reliably

### ISSUE THREAD

**Issue by TylerRick** [jonhue/notifications-rails#54]
## Reliably check if constant exists

Something I noticed when I was stepping through this code a debugger...
```ruby
[11, 20] in notifications-rails/notification-pusher/lib/notification_pusher/pusher.rb
   11:     end
   12: 
   13:     def push(notification, options = {})
   14:       options = @options.merge!(options)
   15: 
=> 16:       return unless defined?(NotificationPusher.const_get(@name))
   17:       instance = NotificationPusher.const_get(@name).new(notification, options)
   18:       @instances << instance
   19:     end
   20: 
(byebug) defined?(NotificationPusher.const_get(@name))
"method"                  
```
What was the `defined?` check for? I assume it's supposed to check if the constant exists under `NotificationPusher`. 

The fact that `defined?` returned `"method"` made me think it's probably actually doing what it was supposed to be doing. Looks like it doesn't actually _perform_ the method call first, so I assume it's the same as doing `defined?(NotificationPusher.const_get)` ... which should always be `true`, I think.

```ruby
main > defined?(ActiveRecord.const_get)
=> "method"
```

Can we just use `const_defined?` for that?

```ruby
main > ActiveRecord.const_defined?(:Base)
=> true

main > ActiveRecord.const_defined?(:Rase)
=> false
```

## Warning: Doesn't trigger autoloading

I ran into this when I was trying to write my own ActionMailer pusher (#53)...

Unless `NotificationPusher::ActionMailer` is already defined when you call `const_get`, it looks like it actually falls back to getting the constant from higher levels. So, until I worked around it by adding:
```ruby
require 'notification_pusher/action_mailer
```

`NotificationPusher.const_get(@name)` was actually returning top-level `::ActionMailer` and causing errors when it tried to use it.

I wonder if there's a way we could safely trigger the const to be autoloaded there? Or _try_ to reference it (to trigger const_missing auto-loading; see example below) but rescue in case it couldn't find it. We could look at what other libraries do; I'm not sure what's typical for that...

Or maybe it's safer to just require it to be `required` like I ended up doing and _not_ try to do anything too automagical. (I know Ruby's `autoload` is going away in Ruby 3. Not sure about Rails's autoloading...)

Anyway, this is what I observed in the debugger session: When I actually *referenced* `NotificationPusher::ActionMailer`, Rails's `const_missing` magic caused the constant to materialize and the subsequent `const_get` to get the correct class...
```ruby
(byebug) NotificationPusher.const_get(@name)
ActionMailer
(byebug) NotificationPusher::ActionMailer
NotificationPusher::ActionMailer
(byebug) NotificationPusher.const_get(@name)
NotificationPusher::ActionMailer
```

**Comment by jonhue** [comment]
Well, here is an option:

```ruby
begin
  instance = NotificationPusher.const_get(@name).new(notification, options)
rescue NameError
  # perhaps it'd be good to raise an exception here
end
```

**Comment by jonhue** [comment]
This:

```
(byebug) NotificationPusher.const_get(@name)
ActionMailer
```

is weird. `NotificationPusher.constants` is only supposed to contain the constants that are defined within itself.

I wasn't able to reproduce it ...

```
[1] pry(main)> class ActionMailer
[1] pry(main)* end
=> nil
[2] pry(main)> module NotificationPusher
[2] pry(main)* end
=> nil
[3] pry(main)> exit
jonhue@Jonas:/c/code/jonhue/jonhue$ be pry
[1] pry(main)> class ActionMailer
[1] pry(main)* end
=> nil
[2] pry(main)> module NotificationPusher
[2] pry(main)*   class ActionMailer
[2] pry(main)*   end
[2] pry(main)* end
=> nil
[3] pry(main)> NotificationPusher.const_get(:ActionMailer)
=> NotificationPusher::ActionMailer
```

**Comment by TylerRick** [comment]
Try this:
```ruby
class ActionMailer
end

module NotificationPusher
end

p NotificationPusher.const_get(:ActionMailer)
# => ActionMailer

module NotificationPusher
  class ActionMailer
  end
end

p NotificationPusher.const_get(:ActionMailer)
# => NotificationPusher::ActionMailer
```

It seems weird at first glance, but once you see that it's probably the exact same lookup logic that's used if you reference an unqualified constant from _inside_ a method (which you do all the time) that's inside a module nesting, then it makes sense...

```ruby
class ActionMailer
  def self.deliver
    'delivered'
  end
end

module NotificationPusher
  class SomeClass
    def push
      p ActionMailer.deliver
    end
  end
end
NotificationPusher::SomeClass.new.push
# => 'delivered'


module NotificationPusher
  class ActionMailer
    def push
    end
  end

  class SomeClass
    def push
      p ActionMailer.deliver
    end
  end
end
NotificationPusher::SomeClass.new.push
# undefined method `deliver' for NotificationPusher::ActionMailer:Class
```

That's why if you want to safely refer to top-level constants from inside a module nesting (if there's any risk there's one with the same name within the nesting you're at), you have to be sure to prefix with `::`, like `::ActionMailer`...

**Comment by TylerRick** [comment]
> Well, here is an option:
> 
> ```ruby
> begin
>   instance = NotificationPusher.const_get(@name).new(notification, options)
> rescue NameError
>   # perhaps it'd be good to raise an exception here
> end
> ```

Exactly. Or just don't rescue it and let it raise a `NameError`.

**Comment by jonhue** [comment]
@TylerRick I sent you an invitation to become a collaborator on this project.
