### ISSUE TITLE
`NotificationSettings.configuration` is nil unless `NotificationSettings.configure` explicitly called; expected it to have default config

### ISSUE THREAD

**Issue by TylerRick** [jonhue/notifications-rails#56]
It's possible to run into errors such as this if you forget to add an initializer that calls `NotificationSettings.configure`:
```
     NoMethodError:
       undefined method `do_not_notify_statuses' for nil:NilClass
     # notification-settings/lib/notification_settings/notification_library.rb:126:in `do_not_notify_statuses'
     # notification-settings/lib/notification_settings/notification_library.rb:39:in `status_allows_create?'
     # notification-settings/lib/notification_settings/notification_library.rb:33:in `can_create?'
     # notification-settings/lib/notification_settings/notification_library.rb:28:in `validate_create'
```

Current implementation doesn't initialize `configuration` unless and until you call `NotificationSettings.configure`:
```ruby
module NotificationSettings
  class << self
    attr_accessor :configuration
  end

  def self.configure
    self.configuration ||= Configuration.new
    yield configuration
  end
```
Should we unconditionally configure NotificationSettings (and the other gems) with the default config so people don't _have_ to call `NotificationSettings.configure` if they just want the defaults? (I think that's the way `RSpec.configure` and most other gems work. We could check how they do it...)

- [ ] Add a unit test that it returns a default `Configuration` object even when `NotificationSettings.configure` not called

**Comment by jonhue** [comment]
I agree. Let's follow the conventions.
