### ISSUE TITLE
Rename Pusher to DeliveryMethod

### ISSUE THREAD

**Issue by TylerRick** [jonhue/notifications-rails#58]
As discussed [here](https://github.com/jonhue/notifications-rails/issues/51#issuecomment-453664827), "delivery method" might be a better, more generic name than "pusher".

One possible naming scheme...

- [ ] Rename gem (and its top-level namespace) to `notification-delivery` (`NotificationDelivery`)??
  - Or leave it as  `notification-pusher` (`NotificationPusher`)?
- [x] Add a namespace under that for delivery methods to be under: `NotificationDelivery::DeliveryMethod`
  - [x] Add an abstract base class that defines the interface (basically just an empty `call` that raises a `NotImplementedError`).`NotificationDelivery::DeliveryMethod::Base`?
  - [x] Move concrete delivery methods under this namespace: `NotificationDelivery::DeliveryMethod::ActionMailer`, etc.

- [x] Rename `NotificationPusher::Pusher` to `NotificationDelivery::DeliveryMethodConfiguration` ([mentioned here](https://github.com/jonhue/notifications-rails/issues/49#issuecomment-453667200))
- [x] Rename `define_pusher` to ~~`define_delivery_method`~~ or `register_delivery_method` (since the _definition_ really happens in the class itself)
- [x] Rename `push` method to `deliver`

I'm certainly open to ideas and discussion!

**Comment by jonhue** [comment]
Just ticked all the boxes ^^

I'm wondering though, whether we really should rename the package/gem/namespace. Maybe it'd be better to limit the changes to the boundaries of the component.

I'm curious as to what's your opinion on this.

**Comment by TylerRick** [comment]
I think I'm fine with that...

If we are going to release a 2.0 release soon with breaking changes (and people are already probably going to be editing their Gemfile if locked to ~1.0), that would be a great opportunity to change gem names if we _wanted_ to...

I think the biggest reason _for_ renaming them would just be consistency: if we're calling them delivery methods _inside_ the gems, would it be better if the _names_ matched that terminology too? Would it feel like they're inconsistent if we _don't_ rename them?

For what it's worth, `notification-pusher-actioncable` does sound like a better name than `notification-delivery-actioncable`.

So yeah, I think I'm currently leaning towards keeping top-level `notification-pusher-*` (`NotificationPusher`) namespace (so we'd end up with constants like `NotificationPusher::DeliveryMethod::ActionMailer`), though I'm a bit conflicted. Maybe give it some more time to think on it and ideally get some more opinions...

**Comment by jonhue** [comment]
I am also leaning towards the `NotificationPusher::DeliveryMethod::ActionMailer` style.
