### ISSUE TITLE
Write specs

### ISSUE THREAD

**Issue by jonhue** [jonhue/notifications-rails#7]

**Comment by TylerRick** [comment]
Just about done a first attempt at adding a test suite (and fixing a few more bugs I've uncovered along the way). Will push up shortly...

**Comment by jonhue** [comment]
This sounds awesome!

**Comment by jonhue** [comment]
@TylerRick how is you progress on that? 😁 Could you perhaps submit a draft pull request so that I can have a look at it too? 🙂
